### ISSUE TITLE
Some improvements / feature requests

### ISSUE THREAD

**Issue by MarvinJWendt** [pratikbutani/WAStickerApp-JSON-Generator#1]
Hey, I like the effort for the tool, but there are some things that I'd like to see in the tool:

1. Automatically update the JSON when an input box value changes
2. A button to copy the whole output JSON to the clipboard (it's hard to select everything when the JSON is long)
3. A better website styling / Layout

<small> I would like to help you out, if you want, but this repository is not up to date with the website, please update it :) </small>

**Comment by pratikbutani** [comment]
@MarvinJWendt Please check latest update with improvement of design and added required functionality.

Quick visit : http://pratikbutani.com/wastickerapp

Hopefully you will like it 👍

**Comment by MarvinJWendt** [comment]
Wow! That's looking awesome @pratikbutani 🚀 
If you want you can add it to the docs at https://github.com/WhatsApp/stickers and create a pull request.
I would be glad to have that accessible to more people :)
Really good work!

**Comment by pratikbutani** [comment]
Thank you so much :+1:

**Comment by pratikbutani** [comment]
@MarvinJWendt May I have to do any changes on pull request or Its remaining to review by other moderator?

**Comment by MarvinJWendt** [comment]
I am just  allowed to approve the changes (which I did) or reject them. I do not have the permission to merge your changes into the master branch. But I am sure that someone will, as soon as they see it :)

**Comment by pratikbutani** [comment]
Thank you for your reply :+1:
